Api call
JohnZHANGFZ/207_group_project pull request #12
Opened 2023-11-13 18:01 UTC by WujiMikeChen

added test files and made code more testable

2023-11-13 22:33 UTC, JohnZHANGFZ commented on src/search_recipe/QueryAPI.java
> +    public static JsonArray getResults(ArrayList<String> ingredients, int number) {
Is it possible for the API to throw exceptions? If Yes then how we are going to deal with this case?

2023-11-19 16:09 UTC, lexazhs reviewed
Overall looks good to me, consider a small change

2023-11-19 16:09 UTC, lexazhs commented on src/database_creation/CreateDatabase.java
>      final ArrayList<String> ingredients;
make them private?

2023-11-20 16:41 UTC, cher-ning commented on src/search_recipe/QueryAPI.java
> +            throw new IOException();
consider changing to file not found exception instead

2023-11-20 16:47 UTC, JohnZHANGFZ commented on src/search_recipe/QueryAPI.java
> +            reader = new BufferedReader(new FileReader(filename));
Good! read the APIKey in this way makes it more private.

2023-11-20 17:11 UTC, JohnZHANGFZ requested changes

2023-11-22 18:46 UTC, lexazhs approved these changes

2023-11-22 20:06 UTC, merged