Entities (except for CommonUserFactory)
JohnZHANGFZ/207_group_project pull request #13
Opened 2023-11-20 17:20 UTC by cher-ning

set up Collection and CollectionFactory interfaces, which are implemented through CommonRestriction, CommonInventory, and CommonRestrictionFactory, CommonInventoryFactory respectively. Set up CommonUser constructor to be used in CommonUserFactory, which will be implemented later on.

2023-11-20 17:23 UTC, WujiMikeChen requested changes

2023-11-20 17:23 UTC, WujiMikeChen commented on src/entity/CommonInventoryFactory.java
> +    }
for non trivial code please comment what the code is doing

2023-11-20 17:39 UTC, JohnZHANGFZ commented on src/entity/CommonInventory.java
> +    CommonInventory() { this.inventory = new ArrayList(); }
consider to make the constructor to be public

2023-11-20 17:41 UTC, JohnZHANGFZ requested changes

2023-11-20 17:41 UTC, JohnZHANGFZ commented on src/entity/CommonInventory.java
> +    public void deleteItems(List<Ingredient> ingredient) {
need to implement this method later

2023-11-20 17:55 UTC, JohnZHANGFZ commented on src/entity/CommonRecipe.java
>      private final Integer rank;
This variable may not necessary if we get the result directly from API

2023-11-23 06:05 UTC, WujiMikeChen commented on src/entity/CommonRestriction.java
Given what input what does this chunk of code do, please comment

2023-11-24 03:19 UTC, WujiMikeChen approved these changes

2023-11-24 19:20 UTC, merged